name: Build
concurrency: build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: rust:bullseye
    continue-on-error: false

    outputs:
      date: ${{ steps.step1.outputs.date }}
      clock: ${{ steps.step1.outputs.clock }}
      tag: ${{ steps.step1.outputs.tag }}
      ref: ${{ steps.step1.outputs.ref }}
      version: ${{ steps.step1.outputs.version }}

    steps:
      - name: Git Clone
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_ALL_REPO }}
          submodules: recursive

      - name: Environment Setup
        id: step1
        shell: bash
        run: |
          echo "version=1.0.$(curl -s -L 'https://carbonmod.gg/version?id=unitask&token=${{secrets.VERSIONS_TOKEN}}')" >> $GITHUB_OUTPUT
          
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.406

      - name: Bootstrap
        shell: bash
        run: |
          cd carbon
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/bootstrap.cs
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/update.cs
          
      - name: Build
        shell: bash
        run: |
          export VERSION=${{ steps.step1.outputs.version }}
          cd carbon
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner ../build/build.cs Release
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner ../build/nuget.cs ${{ secrets.NUGET_API }} Release

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            src/UniTask.NetCore/bin/Release/netstandard2.1/Carbon.UniTask.dll

  release-on-commit:
    name: Release
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
      - name: 🗑️ Delete existing release tag
        uses: dev-drprasad/delete-tag-and-release@92d94d77429cb0436597047a92369526a5824f50
        with:
          delete_release: true
          tag_name: ${{ needs.build.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ALL_REPO }}

      - name: 💤 Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: Release

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: Release

      - name: 🏷️ Update release tag
        uses: softprops/action-gh-release@a92196038060e0c673cf3ba5b98710dd716731df
        with:
          draft: false
          prerelease: false
          tag_name: ${{ needs.build.outputs.version }}
          name: "Carbon.UniTask — v${{ needs.build.outputs.version }}"
          body: |
            wip
          files: |
            Release/build/Carbon.UniTask.dll
